# Copy this file to .streamlit/secrets.toml

# Required
OPENAI_API_KEY = "your-openai-api-key"

# Optional: enable Supabase logging
SUPABASE_URL = "https://your-project.supabase.co"
SUPABASE_SERVICE_KEY = "your-supabase-service-role-key"
# Alternative key name supported
# SUPABASE_KEY = "your-supabase-service-role-key" 